### ISSUE TITLE
Merlin — possible name clash

### ISSUE THREAD

**Issue by little-arhat** [rein/prismriver#1]
Hi, 

Interesting project! 

I've noticed you have used OCaml for lyrica and you're going to name service manager `Merlin`. You probably know that, but there is `Merlin` tool that is used quiet extensively among not very huge OCaml community. So, if you're going to write service manager in OCaml, please, consider that there may be possible confusion.

It's, obviously, just a suggestion, and anyway keep up good work,
Thanks!

**Comment by rein** [comment]
Hi! Thanks for your concern, it was something I had in mind though didn't want to outright address (if I could get away with it).

The project as a whole, and its components, are a reference to [The Prismriver Sisters](http://en.touhouwiki.net/wiki/Prismriver_Sisters), I thought this was quite fitting because they're a musical ensemble and all. I am also not creative in the slightest, and enjoy naming projects after the things I like.

Thus if I change the name of the service manager, effectively I'd need to change the other names too. This is quite a predicament.

To keep the same name, I would advise (and could make this clear) referring to the components with the prefix "prismriver-" or "pr-" both for package managers and discussion. This might help alleviate confusion.

Otherwise, I could rename the project as a whole, but I'd need to think of a suitable set of replacements.

**Comment by rein** [comment]
Since someone else on Reddit wants me to rename it too, I guess I'll change it to Layla, the fourth sister.
